# Generated by Django 4.1.1 on 2022-09-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='catchprhase',
            new_name='catchphrase',
        ),
    ]
